// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kqroqxlvcgnjanuuagkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtxcm9xeGx2Y2duamFudXVhZ2twIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5OTQxNjEsImV4cCI6MjA1NTU3MDE2MX0.nPkoTaExdVL3xVdFfFs4GfS21ASlD6GV_eUgR580Qvw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);